version: '3.9'

services:
  node:
    build: ./docker/node
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app:cached
    # command: sh -c "cd react-sample && yarn start"
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
